#! /usr/bin/env make

myTarget: 
	echo "This will run the first time, but not the second."
	echo "This is because I will create a file, an artifact"
	echo "That make can see has not been updated yet."
	touch myTarget 
